import LeanMetro.Irreducibility
import LeanMetro.PeskunExample

namespace LeanMetro

/-! ## Two-state regression tests for the irreducibility adapter -/

theorem two_state_mh_irreducible :
    twoStateFiniteKernel.Irreducible := by
  constructor
  · exact twoStateFiniteKernel.nonneg
  intro x y
  let : Quiver (Fin 2) := Matrix.toQuiver twoStateFiniteKernel.prob
  have h01 : (0 : Fin 2) ⟶ (1 : Fin 2) :=
    PLift.up (by
      norm_num [twoStateFiniteKernel, twoStateTransition])
  have h10 : (1 : Fin 2) ⟶ (0 : Fin 2) :=
    PLift.up (by
      norm_num [twoStateFiniteKernel, twoStateTransition])
  have h11 : (1 : Fin 2) ⟶ (1 : Fin 2) :=
    PLift.up (by
      norm_num [twoStateFiniteKernel, twoStateTransition])
  fin_cases x <;> fin_cases y
  · exact ⟨(Quiver.Path.nil.cons h01).cons h10, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h01, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h10, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h11, by simp⟩

theorem two_state_lazy_irreducible :
    twoStateLazyKernel.Irreducible := by
  constructor
  · exact twoStateLazyKernel.nonneg
  intro x y
  let : Quiver (Fin 2) := Matrix.toQuiver twoStateLazyKernel.prob
  have h00 : (0 : Fin 2) ⟶ (0 : Fin 2) :=
    PLift.up (by norm_num [twoStateLazyKernel])
  have h01 : (0 : Fin 2) ⟶ (1 : Fin 2) :=
    PLift.up (by norm_num [twoStateLazyKernel])
  have h10 : (1 : Fin 2) ⟶ (0 : Fin 2) :=
    PLift.up (by norm_num [twoStateLazyKernel])
  have h11 : (1 : Fin 2) ⟶ (1 : Fin 2) :=
    PLift.up (by norm_num [twoStateLazyKernel])
  fin_cases x <;> fin_cases y
  · exact ⟨Quiver.Path.nil.cons h00, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h01, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h10, by simp⟩
  · exact ⟨Quiver.Path.nil.cons h11, by simp⟩

/-- The old hand-built MH Poisson inverse is now generated from the standard
finite irreducibility condition. -/
theorem two_state_mh_meanZeroPoissonInvertible_from_irreducible :
    MeanZeroPoissonInvertible twoStateStationary twoStateFiniteKernel := by
  exact meanZeroPoissonInvertible_of_irreducible
    twoStateStationary twoStateFiniteKernel
    (by norm_num [twoStateStationary, Fin.sum_univ_two])
    two_state_mh_reversible.stationary
    two_state_mh_irreducible

/-- The lazy competitor's Poisson inverse is generated by the same adapter. -/
theorem two_state_lazy_meanZeroPoissonInvertible_from_irreducible :
    MeanZeroPoissonInvertible twoStateStationary twoStateLazyKernel := by
  exact meanZeroPoissonInvertible_of_irreducible
    twoStateStationary twoStateLazyKernel
    (by norm_num [twoStateStationary, Fin.sum_univ_two])
    two_state_lazy_reversible.stationary
    two_state_lazy_irreducible

end LeanMetro
